// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

import "github.com/branchkit/plugin-sdk-go"

// ClickButton is a generated enum type.
type ClickButton string

const (
	ClickButtonLeft   ClickButton = "left"
	ClickButtonRight  ClickButton = "right"
	ClickButtonMiddle ClickButton = "middle"
)

// ClickParams is the params shape for action "input.click (Mouse Click)".
type ClickParams struct {
	Button *ClickButton `json:"button,omitempty"`
}

// HandleClick registers a typed handler for action "input.click (Mouse Click)".
func HandleClick(p *branchkit.Plugin, fn func(ClickParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.click", fn)
}

// ClipboardAction is a generated enum type.
type ClipboardAction string

const (
	ClipboardActionCopy  ClipboardAction = "copy"
	ClipboardActionPaste ClipboardAction = "paste"
	ClipboardActionSet   ClipboardAction = "set"
)

// ClipboardParams is the params shape for action "input.clipboard (Clipboard)".
type ClipboardParams struct {
	Action ClipboardAction `json:"action"`
	Text   *string         `json:"text,omitempty"`
}

// HandleClipboard registers a typed handler for action "input.clipboard (Clipboard)".
func HandleClipboard(p *branchkit.Plugin, fn func(ClipboardParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.clipboard", fn)
}

// KeyParams is the params shape for action "input.key (Press Key (Raw Keycode))".
type KeyParams struct {
	Code int `json:"code"`
}

// HandleKey registers a typed handler for action "input.key (Press Key (Raw Keycode))".
func HandleKey(p *branchkit.Plugin, fn func(KeyParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.key", fn)
}

// KeyByNameStrategy is a generated enum type.
type KeyByNameStrategy string

const (
	KeyByNameStrategyKeyEvent KeyByNameStrategy = "key_event"
	KeyByNameStrategyText     KeyByNameStrategy = "text"
)

// KeyByNameParams is the params shape for action "input.key_by_name (Press Key)".
type KeyByNameParams struct {
	Name      string             `json:"name"`
	Modifiers []string           `json:"modifiers,omitempty"`
	Strategy  *KeyByNameStrategy `json:"strategy,omitempty"`
}

// HandleKeyByName registers a typed handler for action "input.key_by_name (Press Key)".
func HandleKeyByName(p *branchkit.Plugin, fn func(KeyByNameParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.key_by_name", fn)
}

// MouseDownButton is a generated enum type.
type MouseDownButton string

const (
	MouseDownButtonLeft   MouseDownButton = "left"
	MouseDownButtonRight  MouseDownButton = "right"
	MouseDownButtonMiddle MouseDownButton = "middle"
)

// MouseDownParams is the params shape for action "input.mouse_down (Mouse Button Down)".
type MouseDownParams struct {
	Button *MouseDownButton `json:"button,omitempty"`
}

// HandleMouseDown registers a typed handler for action "input.mouse_down (Mouse Button Down)".
func HandleMouseDown(p *branchkit.Plugin, fn func(MouseDownParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.mouse_down", fn)
}

// MouseUpButton is a generated enum type.
type MouseUpButton string

const (
	MouseUpButtonLeft   MouseUpButton = "left"
	MouseUpButtonRight  MouseUpButton = "right"
	MouseUpButtonMiddle MouseUpButton = "middle"
)

// MouseUpParams is the params shape for action "input.mouse_up (Mouse Button Up)".
type MouseUpParams struct {
	Button *MouseUpButton `json:"button,omitempty"`
}

// HandleMouseUp registers a typed handler for action "input.mouse_up (Mouse Button Up)".
func HandleMouseUp(p *branchkit.Plugin, fn func(MouseUpParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.mouse_up", fn)
}

// MoveParams is the params shape for action "input.move (Move Cursor)".
type MoveParams struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// HandleMove registers a typed handler for action "input.move (Move Cursor)".
func HandleMove(p *branchkit.Plugin, fn func(MoveParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.move", fn)
}

// RawKeyDirection is a generated enum type.
type RawKeyDirection string

const (
	RawKeyDirectionClick   RawKeyDirection = "click"
	RawKeyDirectionPress   RawKeyDirection = "press"
	RawKeyDirectionRelease RawKeyDirection = "release"
)

// RawKeyParams is the params shape for action "input.raw_key (Raw Key Event)".
type RawKeyParams struct {
	Code      int              `json:"code"`
	Direction *RawKeyDirection `json:"direction,omitempty"`
	Down      *bool            `json:"down,omitempty"`
}

// HandleRawKey registers a typed handler for action "input.raw_key (Raw Key Event)".
func HandleRawKey(p *branchkit.Plugin, fn func(RawKeyParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.raw_key", fn)
}

// ScrollDirection is a generated enum type.
type ScrollDirection string

const (
	ScrollDirectionUp    ScrollDirection = "up"
	ScrollDirectionDown  ScrollDirection = "down"
	ScrollDirectionLeft  ScrollDirection = "left"
	ScrollDirectionRight ScrollDirection = "right"
)

// ScrollUnit is a generated enum type.
type ScrollUnit string

const (
	ScrollUnitLine  ScrollUnit = "line"
	ScrollUnitPixel ScrollUnit = "pixel"
)

// ScrollParams is the params shape for action "input.scroll (Scroll)".
type ScrollParams struct {
	Direction ScrollDirection `json:"direction"`
	Unit      *ScrollUnit     `json:"unit,omitempty"`
	Amount    *int            `json:"amount,omitempty"`
}

// HandleScroll registers a typed handler for action "input.scroll (Scroll)".
func HandleScroll(p *branchkit.Plugin, fn func(ScrollParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.scroll", fn)
}

// ShortcutParams is the params shape for action "input.shortcut (Keyboard Shortcut (Raw Keycode))".
type ShortcutParams struct {
	Code      int      `json:"code"`
	Modifiers []string `json:"modifiers"`
}

// HandleShortcut registers a typed handler for action "input.shortcut (Keyboard Shortcut (Raw Keycode))".
func HandleShortcut(p *branchkit.Plugin, fn func(ShortcutParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.shortcut", fn)
}

// ShortcutByNameStrategy is a generated enum type.
type ShortcutByNameStrategy string

const (
	ShortcutByNameStrategyKeyEvent ShortcutByNameStrategy = "key_event"
	ShortcutByNameStrategyText     ShortcutByNameStrategy = "text"
)

// ShortcutByNameParams is the params shape for action "input.shortcut_by_name (Keyboard Shortcut)".
type ShortcutByNameParams struct {
	Name      string                  `json:"name"`
	Modifiers []string                `json:"modifiers"`
	Strategy  *ShortcutByNameStrategy `json:"strategy,omitempty"`
}

// HandleShortcutByName registers a typed handler for action "input.shortcut_by_name (Keyboard Shortcut)".
func HandleShortcutByName(p *branchkit.Plugin, fn func(ShortcutByNameParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.shortcut_by_name", fn)
}

// TypeParams is the params shape for action "input.type (Type Text)".
type TypeParams struct {
	Text string `json:"text"`
}

// HandleType registers a typed handler for action "input.type (Type Text)".
func HandleType(p *branchkit.Plugin, fn func(TypeParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "input.type", fn)
}
