// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

// ClickButton is a generated enum type.
type ClickButton string

const (
	ClickButtonLeft ClickButton = "left"
	ClickButtonRight ClickButton = "right"
	ClickButtonMiddle ClickButton = "middle"
)

// ClickParams is the params shape for action "input.click (Mouse Click)".
type ClickParams struct {
	Button *ClickButton `json:"button,omitempty"`
}

// ClipboardAction is a generated enum type.
type ClipboardAction string

const (
	ClipboardActionCopy ClipboardAction = "copy"
	ClipboardActionPaste ClipboardAction = "paste"
	ClipboardActionSet ClipboardAction = "set"
)

// ClipboardParams is the params shape for action "input.clipboard (Clipboard)".
type ClipboardParams struct {
	Action ClipboardAction `json:"action"`
	Text *string `json:"text,omitempty"`
}

// KeyParams is the params shape for action "input.key (Press Key (Raw Keycode))".
type KeyParams struct {
	Code int `json:"code"`
}

// KeyByNameStrategy is a generated enum type.
type KeyByNameStrategy string

const (
	KeyByNameStrategyKeyEvent KeyByNameStrategy = "key_event"
	KeyByNameStrategyText KeyByNameStrategy = "text"
)

// KeyByNameParams is the params shape for action "input.key_by_name (Press Key)".
type KeyByNameParams struct {
	Name string `json:"name"`
	Modifiers []string `json:"modifiers,omitempty"`
	Strategy *KeyByNameStrategy `json:"strategy,omitempty"`
}

// MouseDownButton is a generated enum type.
type MouseDownButton string

const (
	MouseDownButtonLeft MouseDownButton = "left"
	MouseDownButtonRight MouseDownButton = "right"
	MouseDownButtonMiddle MouseDownButton = "middle"
)

// MouseDownParams is the params shape for action "input.mouse_down (Mouse Button Down)".
type MouseDownParams struct {
	Button *MouseDownButton `json:"button,omitempty"`
}

// MouseUpButton is a generated enum type.
type MouseUpButton string

const (
	MouseUpButtonLeft MouseUpButton = "left"
	MouseUpButtonRight MouseUpButton = "right"
	MouseUpButtonMiddle MouseUpButton = "middle"
)

// MouseUpParams is the params shape for action "input.mouse_up (Mouse Button Up)".
type MouseUpParams struct {
	Button *MouseUpButton `json:"button,omitempty"`
}

// MoveParams is the params shape for action "input.move (Move Cursor)".
type MoveParams struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// RawKeyDirection is a generated enum type.
type RawKeyDirection string

const (
	RawKeyDirectionClick RawKeyDirection = "click"
	RawKeyDirectionPress RawKeyDirection = "press"
	RawKeyDirectionRelease RawKeyDirection = "release"
)

// RawKeyParams is the params shape for action "input.raw_key (Raw Key Event)".
type RawKeyParams struct {
	Code int `json:"code"`
	Direction *RawKeyDirection `json:"direction,omitempty"`
	Down *bool `json:"down,omitempty"`
}

// ScrollDirection is a generated enum type.
type ScrollDirection string

const (
	ScrollDirectionUp ScrollDirection = "up"
	ScrollDirectionDown ScrollDirection = "down"
	ScrollDirectionLeft ScrollDirection = "left"
	ScrollDirectionRight ScrollDirection = "right"
)

// ScrollParams is the params shape for action "input.scroll (Scroll)".
type ScrollParams struct {
	Direction ScrollDirection `json:"direction"`
	Amount *int `json:"amount,omitempty"`
}

// ShortcutParams is the params shape for action "input.shortcut (Keyboard Shortcut (Raw Keycode))".
type ShortcutParams struct {
	Code int `json:"code"`
	Modifiers []string `json:"modifiers"`
}

// ShortcutByNameStrategy is a generated enum type.
type ShortcutByNameStrategy string

const (
	ShortcutByNameStrategyKeyEvent ShortcutByNameStrategy = "key_event"
	ShortcutByNameStrategyText ShortcutByNameStrategy = "text"
)

// ShortcutByNameParams is the params shape for action "input.shortcut_by_name (Keyboard Shortcut)".
type ShortcutByNameParams struct {
	Name string `json:"name"`
	Modifiers []string `json:"modifiers"`
	Strategy *ShortcutByNameStrategy `json:"strategy,omitempty"`
}

// TypeParams is the params shape for action "input.type (Type Text)".
type TypeParams struct {
	Text string `json:"text"`
}

