// AUTO-GENERATED by branchkit-gen — do not edit.
// Source: plugin.json `consumes.collections` field claims, typed from
// each provider's declared schema. Run: just gen-plugins

package main

// PlatformKeyNamesRecord is the shape this plugin declared it reads from the
// "_platform.key_names" collection. Unmarshal a CollectionRecord's Payload into it.
type PlatformKeyNamesRecord struct {
	Name string `json:"name"`
	Code int    `json:"code"`
}
